apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
    app: webapp
  namespace: {{ include "webapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: "{{ .Values.env.name }}"
          value: "{{ .Values.env.value }}"
        readinessProbe:
          httpGet:
            path: /id
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /id
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30