apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp.fullname" . }}
  namespace: {{ include "webapp.fullname" . }}
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 8000
    targetPort: 8000
