kind: Namespace
apiVersion: v1
metadata:
  name: test
  labels:
    name: test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
  namespace: test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: ilnar20/webapp:latest
        ports:
        - containerPort: 8000
        # livenessProbe:
        #   httpGet:
        #     path: /id
        #     port: 8000
        #   failureThreshold: 1
        #   periodSeconds: 60
        #   # Override pod-level terminationGracePeriodSeconds #
        #   terminationGracePeriodSeconds: 60
        env:
        - name: UUID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 1
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: test
spec:
  selector:
    app: webapp
  ports:
  - name: http
    port: 8000
    targetPort: 8000
